from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class SkillManifest:
    name: str
    source: str
    created_at: str
    taxonomy: dict
    permissions: dict
    uncertainty_notes: list[str]
    verifier_prompts: list[str]


def slugify(value: str) -> str:
    return "-".join("".join(c.lower() if c.isalnum() else " " for c in value).split()) or "skill"


def build_manifest(source: str, name: str) -> SkillManifest:
    is_recent = source.startswith("recent-context:")
    return SkillManifest(
        name=name,
        source=source,
        created_at=datetime.now(timezone.utc).isoformat(),
        taxonomy={
            "inputs": ["repository path", "docs path", "URL", "topic"],
            "outputs": ["skill manifest", "README", "verifier prompt"],
            "freshness_needs": "high" if is_recent else "medium",
            "failure_modes": ["stale sources", "missing citations", "overbroad permissions"],
        },
        permissions={"filesystem_read": True, "filesystem_write": True, "network": source.startswith(("http://", "https://", "recent-context:"))},
        uncertainty_notes=["Starter output: review generated claims and add citations before sharing."],
        verifier_prompts=[
            "Check that every factual claim has a source or is marked uncertain.",
            "Check that required permissions are minimal and explicit.",
        ],
    )


def write_skill(source: str, name: str, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(source, name)
    (out / "skill.json").write_text(json.dumps(asdict(manifest), indent=2) + "\n", encoding="utf-8")
    (out / "README.md").write_text(
        f"# {name}\n\nGenerated by SkillForge from `{source}`.\n\n"
        "## Verify\n\nRun the prompts in `verifier.md` before publishing.\n",
        encoding="utf-8",
    )
    (out / "verifier.md").write_text("\n".join(f"- {p}" for p in manifest.verifier_prompts) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a portable AI agent skill pack.")
    parser.add_argument("source", help="Repo/docs path, URL, or 'recent-context: <topic>'")
    parser.add_argument("--name", help="Skill name")
    parser.add_argument("--out", default="dist/skill", help="Output directory")
    args = parser.parse_args(argv)

    name = args.name or slugify(args.source.replace("recent-context:", ""))
    write_skill(args.source, name, Path(args.out))
    print(f"Wrote skill pack to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
